import * as React from "react";
import { useContext, useEffect, useState } from "react";
import { styled } from '@mui/material/styles';
import Paper from "@mui/material/Paper";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell, { tableCellClasses } from '@mui/material/TableCell';
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TablePagination from "@mui/material/TablePagination";
import TableRow from "@mui/material/TableRow";
import styles from './Realtime.module.css';
import { Context } from "../../context/Contexts";
import RealTime from "../AI Models/Prediction Model/RealTime";

const StyledTableCell = styled(TableCell)(({ theme }) => ({
    [`&.${tableCellClasses.head}`]: {
        backgroundColor: theme.palette.common.black,
        color: theme.palette.common.white,
    },
    [`&.${tableCellClasses.body}`]: {
        fontSize: 14,
    },
}));

const columns = [
    { id: "name", label: "Data Feeds", minWidth: 170 },
    { id: "code", label: "Type", minWidth: 100 },
    {
        id: "population",
        label: "Description",
        minWidth: 170,
        align: "right",
        format: (value) => value.toLocaleString("en-US")
    },

];
// const [component, setComponent] = useState();

function createData(name, code, population) {
    return { name, code, population };
}

function clickComponent() {
    console.log('Hello');

}

const rows = [
    createData(<a href="/models/realtime_model"> Carbon Intensity</a>, "Realtime (Regional)", "Carbon Intensity for UK Region"),
    createData(<a href="/models/EnergyFrequency"> Energy Frequency</a>, "Realtime (National)", "Energy Frequency for UK from Elexon"),
    createData(<a href="/models/EnergyDemand"> Energy Demand</a>, "Realtime (National)", "Energy Demand for UK from Elexon"),
    createData(<a href="/models/WindProduction"> Wind Production</a>, "Realtime (Regional)", "Wind Energy Value for UK from Elexon",

    ),
    createData(<a href="/models/SolarEnergyProduction"> Solar Energy Production</a>, "Realtime (Regional)", "Wind Energy Value for UK from Elexon",

    ),
    createData(<a href="/models/DailyEnergyTransmit"> Daily Energy Transmit</a>, "Realtime (Regional)", "Energy Transmission Value of UK"),
    createData(<a href="/models/EnergyGeneratedByFuel"> Energy Generated By Fuel</a>, "Realtime (National)", "Energy Generated by Fuel for UK from Elexon",

    ),
    createData(<a href="/models/EnergyPrice"> Energy Price</a>, "Realtime (National)", "Energy Price for UK from Elexon"),
    createData("Weather", "Realtime (Regional)", "Weather Data for UK"),
    createData(
        "STOR DA Auction result",
        "Realtime (National)",
        "Auction Result for UK from National Grid ESO",


    ),
    createData(
        "Historic GTMA Trades Data",
        "Realtime (National)",
        "Trade data for UK from National Grid ESO",

    ),
    createData(" Daily Balancing Cost", "Realtime (National)", "Balancing Cost of Energy for UK"),
    createData(
        "Current Settlement Final BSUoS Data",
        "Realtime (National)",
        "Daily Balancing Cost for UK from National Grid ESO",

    ),
];

export default function Realtime() {
    const context = useContext(Context);
    useEffect(() => {
        context.setShowNavTop(true);
    }, [context]);

    const [page, setPage] = React.useState(0);
    const [rowsPerPage, setRowsPerPage] = React.useState(10);

    const handleChangePage = (event, newPage) => {
        setPage(newPage);
    };

    const handleChangeRowsPerPage = (event) => {
        setRowsPerPage(+event.target.value);
        setPage(0);
    };

    return (
        <div className={[styles.register, context.close ? styles.close : ""].join(" ")}>
            <Paper sx={{ width: "100%" }}>
                <TableContainer sx={{ maxHeight: 440 }}>
                    <Table stickyHeader aria-label="sticky table">
                        <TableHead>
                            <TableRow>
                                <StyledTableCell align="center" colSpan={12} style={{ fontWeight: "bold", fontSize: "25px" }}>
                                    Kendra Sustain Data Feeds
                                </StyledTableCell>
                                {/* <TableCell align="center" colSpan={3}>
                Details
              </TableCell> */}
                            </TableRow>
                            <TableRow>
                                {columns.map((column) => (
                                    <TableCell
                                        key={column.id}
                                        align={column.align}
                                        style={{ top: 57, minWidth: column.minWidth }}
                                    >
                                        {column.label}
                                    </TableCell>
                                ))}
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {rows
                                .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                                .map((row) => {
                                    return (
                                        <TableRow hover role="checkbox" tabIndex={-1} key={row.code}>
                                            {columns.map((column) => {
                                                const value = row[column.id];
                                                return (
                                                    <TableCell key={column.id} align={column.align}>
                                                        {column.format && typeof value === "number"
                                                            ? column.format(value)
                                                            : value}
                                                    </TableCell>
                                                );
                                            })}
                                        </TableRow>
                                    );
                                })}
                        </TableBody>
                    </Table>
                </TableContainer>
                <TablePagination
                    rowsPerPageOptions={[10, 25, 100]}
                    component="div"
                    count={rows.length}
                    rowsPerPage={rowsPerPage}
                    page={page}
                    onPageChange={handleChangePage}
                    onRowsPerPageChange={handleChangeRowsPerPage}
                />
            </Paper>
            {/* <button>Click Me</button> */}
        </div>
    );
}