export { default as Features } from './Features'
export { default as Footer } from './Footer'
export { default as NewsLatter } from './NewsLatter'
export { default as Organize } from './Organize'
export { default as Partners } from './Partners'
export { default as HomeDetails } from './HomeDetails'
export { default as Testimonial } from './Testimonial'
